/**
 * The Chat box API.
 *
 * AUTHORIZATION IS MOUNTED ONCE, ON THE PREFIX, so a route added later cannot
 * be forgotten: everything under /chat requires a signed-in ADMIN or
 * RECEPTIONIST. Bộ phận đặt phòng calling any of these directly gets 403 —
 * hiding the menu is not the control, this is.
 *
 * The service layer re-checks the role and re-applies the per-user visibility
 * filter on every call as well. That is deliberate belt-and-braces: the
 * middleware protects the HTTP surface, `assertChatAccess` + `visibilityWhere`
 * protect the domain even if something else ever calls it.
 *
 * NO REALTIME TRANSPORT. The application has no WebSocket or SSE anywhere, and
 * introducing one for this would add a connection lifecycle, an auth handshake
 * and a reconnect story to a feature whose traffic is a handful of messages a
 * day. The client polls these endpoints instead — the simplest thing that is
 * reliable on the existing stack.
 */
import { Router } from 'express';
import type { Request } from 'express';
import { z } from 'zod';
import { requireAuth, requirePasswordChanged, requireRole } from '../middleware/auth';
import { chatUpload } from '../middleware/upload';
import { ApiError } from '../lib/errors';
import {
  addMessage,
  closeConversation,
  createConversation,
  getConversation,
  listConversations,
  listMessages,
  authorizeChatAttachment,
  type ChatActor,
  type NewAttachment,
} from '../chat/chatService';
import { generateChatFileName, readChatFile, saveChatFile, sniffChatMime } from '../chat/chatStorage';

function actorOf(req: Request): ChatActor {
  const user = req.currentUser;
  if (!user) throw ApiError.authRequired();
  return { id: user.id, role: user.role, branchId: user.branchId ?? null };
}

function idOf(raw: string | undefined): string {
  if (!raw || raw.trim().length === 0) throw ApiError.notFound('Không tìm thấy cuộc trò chuyện.');
  return raw;
}

const createSchema = z.object({
  subject: z.string().trim().min(1, 'Vui lòng nhập tiêu đề.').max(200),
  // May be empty when images are attached; the service decides.
  body: z.string().max(5000).optional().default(''),
});

const messageSchema = z.object({
  body: z.string().max(5000).optional().default(''),
});

/**
 * Sniffs, names and writes every uploaded image, returning the rows to attach.
 *
 * THE REAL TYPE DECIDES, not the declared one — a renamed executable is
 * rejected here, before anything reaches disk or the database.
 *
 * EVERY FILE IS CHECKED BEFORE ANY FILE IS WRITTEN. The obvious loop — sniff,
 * write, repeat — leaves the first two images on disk when the third turns out
 * to be a renamed executable: the request fails, no database row is ever
 * created, and those bytes are unreferenced by anything and so are never
 * cleaned up. Rejecting the whole batch up front makes the write-out
 * all-or-nothing in the only case that can realistically fail.
 */
async function persistUploads(req: Request, conversationId: string): Promise<NewAttachment[]> {
  const files = (req.files as Express.Multer.File[] | undefined) ?? [];

  // Pass 1 — validate everything. Nothing has touched the disk yet.
  const checked = files.map((file) => {
    const mime = sniffChatMime(file.buffer);
    if (!mime) {
      throw ApiError.unsupportedMedia('Chỉ chấp nhận ảnh PNG, JPEG hoặc WebP.');
    }
    return { file, mime };
  });

  // Pass 2 — write. `saveChatFile` uses the `wx` flag, so a name collision
  // fails loudly rather than overwriting an existing attachment.
  const saved: NewAttachment[] = [];
  for (const { file, mime } of checked) {
    const storedFileName = generateChatFileName(conversationId, mime);
    await saveChatFile(file.buffer, storedFileName);
    saved.push({
      storedFileName,
      originalFileName: file.originalname,
      mimeType: mime,
      fileSize: file.size,
    });
  }
  return saved;
}

export function createChatRouter(): Router {
  const router = Router();

  // ONE gate for the whole module.
  router.use('/chat', requireAuth, requirePasswordChanged, requireRole('ADMIN', 'RECEPTIONIST'));

  // GET /api/chat/conversations — the caller's visible threads, newest first.
  router.get('/chat/conversations', (req, res, next) => {
    (async () => {
      res.json({ conversations: await listConversations(actorOf(req)) });
    })().catch(next);
  });

  // POST /api/chat/conversations — receptionist opens a thread (multipart).
  router.post('/chat/conversations', chatUpload(), (req, res, next) => {
    (async () => {
      const actor = actorOf(req);
      const input = createSchema.parse(req.body ?? {});
      // A cuid is generated by the database, so the file name is seeded with a
      // per-request token instead; the id is only ever a readability prefix.
      const attachments = await persistUploads(req, 'new');
      const result = await createConversation(
        { subject: input.subject, body: input.body, attachments },
        actor,
      );
      res.status(201).json(result);
    })().catch(next);
  });

  // GET /api/chat/conversations/:id
  router.get('/chat/conversations/:id', (req, res, next) => {
    (async () => {
      res.json({ conversation: await getConversation(idOf(req.params.id), actorOf(req)) });
    })().catch(next);
  });

  // GET /api/chat/conversations/:id/messages — what the client polls.
  router.get('/chat/conversations/:id/messages', (req, res, next) => {
    (async () => {
      res.json({ messages: await listMessages(idOf(req.params.id), actorOf(req)) });
    })().catch(next);
  });

  // POST /api/chat/conversations/:id/messages — reply or follow-up (multipart).
  router.post('/chat/conversations/:id/messages', chatUpload(), (req, res, next) => {
    (async () => {
      const actor = actorOf(req);
      const id = idOf(req.params.id);
      // Confirms the thread exists and the caller may reach it BEFORE any file
      // is written — otherwise a stranger's id would still cost us disk.
      await getConversation(id, actor);
      const input = messageSchema.parse(req.body ?? {});
      const attachments = await persistUploads(req, id);
      const message = await addMessage(id, { body: input.body, attachments }, actor);
      res.status(201).json({ message });
    })().catch(next);
  });

  // POST /api/chat/conversations/:id/close — Admin only.
  router.post('/chat/conversations/:id/close', (req, res, next) => {
    (async () => {
      res.json({ conversation: await closeConversation(idOf(req.params.id), actorOf(req)) });
    })().catch(next);
  });

  /**
   * GET /api/chat/attachments/:attachmentId/file — the bytes.
   *
   * Authenticated and visibility-checked like everything else, `private,
   * no-store` so an image is never cached by a proxy, and `nosniff` so a stored
   * file cannot be coerced into executing as something else. There is no public
   * URL for these files anywhere.
   */
  router.get('/chat/attachments/:attachmentId/file', (req, res, next) => {
    (async () => {
      const attachment = await authorizeChatAttachment(
        idOf(req.params.attachmentId),
        actorOf(req),
      );
      const bytes = await readChatFile(attachment.storedFileName);
      res.setHeader('Content-Type', attachment.mimeType);
      res.setHeader('Cache-Control', 'private, no-store');
      res.setHeader('X-Content-Type-Options', 'nosniff');
      res.setHeader('Content-Disposition', 'inline');
      res.send(bytes);
    })().catch(next);
  });

  return router;
}
